name = "asapm"
type = "javascript"
workers_dev = true
compatibility_date = "2022-01-16"
kv_namespaces = [
    # replace your namespaces here (or use miniflare)
    { binding = "password", preview_id = "", id = "" },
    { binding = "user", preview_id = "", id = "" }
]

[vars]
WORKERS_RS_VERSION = "0.0.7"
SECRET = "YOUR SUPER DUPER SECRET JWT KEY"

[build]
# the sed fixes the usage of 'performance.now()' by jwt-simple
# it got banned by cloudflare due possbile timing attacks
command = "cargo install -q worker-build && worker-build --release && sed -i 's/performance.now()/Date.now()/' build/worker/index_bg.mjs" # required

[build.upload]
dir    = "build/worker"
format = "modules"
main   = "./shim.mjs"

[[build.upload.rules]]
globs = ["**/*.wasm"]
type  = "CompiledWasm"

# read more about configuring your Worker via wrangler.toml at:
# https://developers.cloudflare.com/workers/cli-wrangler/configuration
