on: [pull_request]

name: Linter

defaults:
  run:
    working-directory: ./app/src-tauri/

jobs:
  rustfmt:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo fmt --all -- --check
