on: [pull_request]

name: Tests

defaults:
  run:
    working-directory: ./app/src-tauri/

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        platform: [ macos-latest, ubuntu-latest, windows-latest ]
    name: Tests
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install -y libgtk-3-dev libwebkit2gtk-4.0-dev
      - name: Create empty dist
        run: mkdir ../dist
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path ./app/src-tauri/Cargo.toml
